{
  "db825ba62b1e09e5292c0990fccbb807" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "ff3373a704c681b9",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='ehashapi.test.poolx.io', port=81): Max retries exceeded with url: /pool//v1/miner/Home (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff278a56f90>: Failed to establish a new connection: [Errno 61] Connection refused'))",
      "time" : {
        "start" : 1663321374093,
        "stop" : 1663321374148,
        "duration" : 55
      }
    } ]
  }
}